# Change these first
owner: S409ISDAD # Your GitHub organization or username, where this repository lives
repo: zink-uptime # The name of this repository

sites:
  - name: Shard Jayden
    url: https://zb.409409409.xyz
  - name: Shard Daniel
    url: https://zink-bot-production.onrender.com
  - name: Shard Jack
    url: https://zink-bot-porductution.onrender.com
  - name: Shard Ava
    url: http://45.87.172.181:2898
  - name: Shard Robbie
    url: http://dono-01.danbot.host:2047
  - name: Shard Cole
    url: http://deka.pylex.software:9886
  - name: Shard Sophia
    url: http://192.99.10.133:6894
  - name: Shard Jacob
    url: https://zink-bot.onrender.com
  - name: Shard Cameron
    url: http://cameron.zinkhost.cloud:22565
  - name: Shard Lewis
    url: http://lewis.zinkhost.cloud:22565
  - name: Shard Ethan
    url: http://ethan.zinkhost.cloud:22565
  - name: Shard Lucas
    url: http://lucas.zinkhost.cloud:22565
  

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.zinkhost.cloud
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Zink But Uptime**"
  introMessage: Here you can view the uptime of our various shards!
  navbar:
    - title: Status
      href: /
    - title: Invite
      href: https://discord.com/oauth2/authorize?client_id=1243634051873636505

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
